apiVersion: batch/v1
kind: Job
metadata:
  name: flag-db-init-job
  namespace: toggle-master
spec:
  template:
    spec:
      containers:
      - name: postgres-init
        image: postgres:15-alpine
        command:
        - "sh"
        - "-c"
        - |
          psql "postgres://postgres:Gio123vani-flag@172.31.9.12:5432/postgres" -c "
          DROP TABLE IF EXISTS flags CASCADE;
          CREATE TABLE flags (
              id SERIAL PRIMARY KEY,
              name VARCHAR(100) NOT NULL,
              description TEXT,
              is_enabled BOOLEAN NOT NULL DEFAULT false,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
          );"
      restartPolicy: Never
  backoffLimit: 4