apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation-service
type: Opaque
data:
  REDIS_URL: "REDIS_URL-EM-BASE64"
  SERVICE_API_KEY: "SERVICE_API_KEY-EM-BASE64" 
  AWS_SQS_URL: "AWS_SQS_URL-EM-BASE64"
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID-EM-BASE64"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY-EM-BASE64"
  AWS_SESSION_TOKEN: "AWS_SESSION_TOKEN-EM-BASE64"

