apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: toggle-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
      - name: evaluation-service
        # Substitua com a URL exata do seu repositório ECR da Etapa 2
        image: 121590089702.dkr.ecr.us-east-1.amazonaws.com/namespace/evaluation-service:latest
        ports:
        - containerPort: 8004 # Ajuste para a porta que seu microsserviço Go ouve
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 20
        # Injeção das variáveis de ambiente a partir do ConfigMap e Secret
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: REDIS_URL
        - name: AUTH_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: AUTH_SERVICE_URL
        - name: FLAG_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: FLAG_SERVICE_URL
        - name: TARGETING_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: TARGETING_SERVICE_URL
        - name: SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: SERVICE_API_KEY
        - name: AWS_SQS_URL
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: AWS_SQS_URL
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: evaluation-secret
              key: AWS_SESSION_TOKEN
        # Requisito de boas práticas do desafio (Requests e Limits)
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: toggle-master
spec:
  type: ClusterIP # Exigido no PDF do desafio
  ports:
  - port: 8004
    targetPort: 8004
  selector:
    app: evaluation-service