apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: toggle-master
type: Opaque
data:
  # Cole aqui o código em Base64 gerado no Passo 1
  REDIS_URL: "cmVkaXNzOi8vY2x1c3RlcmNmZy5yZWRpcy1ldmFsdWF0aW9uLmh0dmtyay51c2UxLmNhY2hlLmFtYXpvbmF3cy5jb206NjM3OQ=="
  AUTH_SERVICE_URL: "aHR0cDovL2F1dGgtc2VydmljZTo4MDAx"
  FLAG_SERVICE_URL: "aHR0cDovL2ZsYWctc2VydmljZTo4MDAy"
  TARGETING_SERVICE_URL: "aHR0cDovL3RhcmdldGluZy1zZXJ2aWNlOjgwMDM="
  SERVICE_API_KEY: "dG1fa2V5X2Y0ODBhNmUzOTljMDFlMzY0YWE3ZWY3NDZlMzc0ZjQ0MTY2MTI0Zjk5YmQ3NTEzN2JhZjU3Yjk3YmZiNmU0MGM="
  AWS_SQS_URL: "aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMTIxNTkwMDg5NzAyL2V2YWx1YXRpb24tcXVldWU="
  AWS_REGION: "dXMtZWFzdC0x"
  AWS_ACCESS_KEY_ID: "QVNJQVJZVDJWUTdURzZJTkpQWUg="
  AWS_SECRET_ACCESS_KEY: "V1dyOGtTVlZmUkpHRFc0ZTdGbEMydXdvSENZcThSV3FCbUtXUGhUeA=="
  AWS_SESSION_TOKEN: "SVFvSmIzSnBaMmx1WDJWakVMUC8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpHTUVRQ0lGV0pkMjA0MXQxS0I4amFKT2RoZlgra1RBbE0wNjBzeXZoeXljNEpqUHRZQWlCYTJqbjh6U1BaSy94TzdkbmY1SVllb3d3RFRIZ2hwanFMdGFKUmkzRUZHeXF3QWdoOEVBRWFEREV5TVRVNU1EQTRPVGN3TWlJTW1pRjZUTnJ2TlpERWZIWURLbzBDVGFwQTdvTGllMnRqVGlSOUxpSHhzbDg0N3VoMVM1OXBtcVNwUlphdjBHVUVVUC9tc2lSTlNzN0t3NE5CeDVhTVRkVFJmVkgyV09LY2RLSTNwODczVG8wNHFHVkFTalVvY25QU2hpVGpqdm50bjgvY2xobHVSS0dFa09XVmF0bHNsZE4ySG9WRTN2RXAzUGRSaWFRNkpoVWlBR0IxdlpmMWZXN09NR0dkdUNmcWpmdm1haFlnSk94Y1AvaGpPbElLYUZWRnJNeEZaSkpPdm9tOGN0MklldWt1YXN1RWxOVHk1a241Q05rSXBlYTQzNUgrZWM4WERTZnlNc0x3RlpLZE9sYk5mNXJLZWFScktZdUhuMGxZcGNWTHZOZUNSR3lhd2ZJOW5tdVpmUXlIRUhzWGdUaFg3bTEweDFJcGw1VDAvMG10aXpOenhvR01sSEo0aktXMEJQcDBBb01kTXBZZzNHdUV4RUl3NmVtMjBnWTZuZ0hvRHVTcU9rTUpaQlB6eVRJVVZvYXdrN3U0Y0IwNFNKbEFOOXdqb1V3dU1tU0FXNDkrWXp5ZDlmVDM1T2pHQWFvMUt1TTBMbXBEdkIyRkhjUG1YUVBwTVg5MGZrdFBuMTc1U1Ewam5NS3g4NlFTdmVpcGlETEVybjUrYXlBMkJHZkZ1aFUvcmp2RytYZWpRNHdlSkR2S3dpeXNwZlhsbFZMR1VSTnJQMVN5cXNnMldtb0oxUTg2UE5LZnI0ZmlzdjNUMEtyakhjRE1MaGUyemR5bWRRPT0="