---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics-service
type: Opaque
data:
  AWS_SQS_URL: "AWS_SQS_URL-EM-BASE64"
  AWS_DYNAMODB_TABLE: "AWS_DYNAMODB_TABLE-EM-BASE64"
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID-EM-BASE64"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY-EM-BASE64"
  # Em caso de AWS ACADEMY
  AWS_SESSION_TOKEN: "AWS_SESSION_TOKEN-EM-BASE64"