apiVersion: v1
kind: Namespace
metadata:
  name: toggle-master
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: toggle-master
data:
  DB_USER: "postgres"
  DB_PORT: "5432"
  DB_NAME: "postgres"  # Nome padrão do banco inicial do RDS
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: toggle-master
type: Opaque
data:
  MASTER_KEY: "YWRtaW4tc2VjcmV0by0xMjM="
  DATABASE_URL: "cG9zdGdyZXM6Ly9wb3N0Z3JlczpHaW8xMjN2YW5pQDE3Mi4zMS43MS44NDo1NDMyL3Bvc3RncmVz"