apiVersion: batch/v1
kind: Job
metadata:
  name: auth-db-init-job
  namespace: toggle-master
spec:
  template:
    spec:
      containers:
      - name: postgres-init
        image: postgres:15-alpine
        command:
        - "sh"
        - "-c"
        - |
          psql "postgres://postgres:Gio123vani@172.31.71.84:5432/postgres" -c "
          DROP TABLE IF EXISTS api_keys CASCADE;
          CREATE TABLE api_keys (
              id SERIAL PRIMARY KEY,
              name VARCHAR(100) NOT NULL,
              key_hash VARCHAR(64) NOT NULL UNIQUE, 
              is_active BOOLEAN DEFAULT true,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
          );"
      restartPolicy: Never
  backoffLimit: 4