apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-scaledobject
  namespace: analytics-service
spec:
  scaleTargetRef:
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 60
  pollingInterval: 30
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/628409561285/evaluation
        queueLength: "5"
        awsRegion: "us-east-1"
      authenticationRef:
        name: keda-trigger-auth-aws