apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth-service
type: Opaque
data:
  DATABASE_URL: "REFUQUJBU0VfVVJMLUVNLUJBU0U2NA=="
  MASTER_KEY: "TUFTVEVSX0tFWS1FTS1CQVNFNjQ="
